baseURL = "https://devrelcollective.fun/"
#baseURL = "https://elegant-kilby-ac915a.netlify.app/"
languageCode = "en-us"
title = "The DevRel Collective"
theme = "avocado"
googleAnalytics = "UA-113313834-3"